### ISSUE TITLE
An established connection was aborted by the software in your host machine

### ISSUE THREAD

**Issue by ixworks** [pdftables/python-pdftables-api#28]
Error:  An established connection was aborted by the software in your host machine

Traceback (most recent call last):
  File "D:/Arbeit/parsererods.py", line 4, in <module>
    c.xlsx('sprugk4d.pdf', 'output.xlsx')
  File "D:\Users\jamie\AppData\Local\Programs\Python\Python39\lib\site-packages\pdftables_api\pdftables_api.py", line 59, in xlsx
    return self.xlsx_multiple(pdf_path, xlsx_path)
...
...

requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None))

**Comment by ixworks** [comment]
disregard...need api key, I think
